// Source data for the 64 hexagram pages. Run generate.mjs after editing this
// file to regenerate the static pages under /hexagrams/.
//
// unicode: each hexagram has a dedicated Unicode glyph in the "Yijing Hexagram
// Symbols" block (U+4DC0-U+4DFF), ordered by King Wen sequence, so hexagram N
// is always U+4DC0 + (N - 1).

function symbol(number) {
  return String.fromCodePoint(0x4dc0 + (number - 1));
}

const RAW = [
  ["The Creative", "Qián", "Pure, unbroken yang energy. Creative power in its most concentrated form — initiative, leadership, and the drive to originate rather than follow.", "Heaven moves with untiring strength; the wise act with the same tireless, self-renewing energy.", "This is a moment to lead rather than wait. Trust the strength of your own initiative, but temper it with patience — pure creative force needs a season to mature before it can be sustained."],
  ["The Receptive", "Kūn", "Pure, unbroken yin energy. Where the Creative initiates, the Receptive completes — strength expressed through devotion, patience, and the capacity to yield without losing form.", "The earth's condition is receptive devotion; the wise carry the world by supporting it rather than forcing it.", "Progress now comes through openness, not force. Let yourself follow the shape of the situation for a while — support what is already moving before trying to redirect it."],
  ["Difficulty at the Beginning", "Zhūn", "The chaotic, formless energy of anything genuinely new — a birth, a venture, a relationship still finding its shape. Difficulty here is not failure; it is what growth looks like at the start.", "Clouds and thunder: the image of a difficult beginning that is nonetheless full of potential.", "Don't mistake early confusion for a wrong path. Move in small, deliberate steps, gather trustworthy help, and give the situation time to organize itself."],
  ["Youthful Folly", "Méng", "Inexperience meeting the world for the first time. Not foolishness as failure, but the natural, necessary not-knowing that precedes real understanding.", "A spring rises at the foot of the mountain: the image of youth, and of a source that has not yet found its course.", "It is safe to admit what you don't yet know. Seek a teacher or mentor sincerely, and stay teachable — the answer will come through patient learning, not forcing certainty."],
  ["Waiting", "Xū", "Nourishment gathering before action. The situation is not yet ripe, and pushing forward now would be premature — the wisest move is confident, well-fed patience.", "Clouds rise up to heaven: the image of waiting for the rain that is already forming.", "You've done the preparation; now let the timing catch up to your readiness. Rest, eat well, keep your strength — the moment to act is close but not yet here."],
  ["Conflict", "Sòng", "Opposition and dispute, often arising when two parties both feel justified. The hexagram warns against pursuing conflict to a bitter end, even when you believe you're right.", "Heaven and water move in opposing directions: the image of estrangement, and of a dispute that both sides should seek to settle early.", "Look for a fair middle ground before the disagreement hardens. Being technically right is not the same as being at peace — resolution serves you better than victory."],
  ["The Army", "Shī", "Disciplined collective effort, mobilized carefully and only for a just cause. Strength lies in organization and a trustworthy leader, not in raw numbers.", "In the middle of the earth is water: the image of the masses, gathered and given direction.", "If you're rallying people or resources toward a goal, lead with clear discipline and fairness. Numbers alone don't win — coordinated, well-led effort does."],
  ["Holding Together", "Bǐ", "Union built on genuine trust. People or efforts come together not by coercion but because they recognize a shared center worth gathering around.", "Water flows freely over the earth: the image of things naturally joining together, without forcing.", "Strengthen the bonds you already have rather than chasing new alliances. If you're the one others are gathering around, lead with sincerity — that is what holds a union together."],
  ["The Taming Power of the Small", "Xiǎo Chù", "Restraint exercised through gentle, gradual influence rather than force — like wind that shapes without breaking. Progress is real, but modest, for now.", "Wind moves across heaven: the image of small, accumulating restraint that has not yet become a storm.", "Big moves aren't available yet, but small, consistent ones are. Refine your approach in quiet ways; the larger breakthrough will come once these smaller adjustments accumulate."],
  ["Treading", "Lǚ", "Careful conduct in a delicate situation — like walking directly behind a tiger. Success depends on tact, correct behavior, and not provoking what could turn on you.", "Heaven above, the lake below: the image of clear distinction between high and low, and of conduct that respects it.", "Mind your step in situations involving power imbalance or sensitive relationships. Courteous, careful behavior will see you through safely where bluntness would not."],
  ["Peace", "Tài", "A season of harmony, when opposing forces — heaven and earth, effort and receptivity — are in genuine, generative exchange. One of the most auspicious hexagrams.", "Heaven and earth unite: the image of a time when what is above and what is below meet each other freely.", "Things are flowing well — use this season to build durable foundations, not just enjoy the ease. Peace is a cycle, not a permanent state, so invest it wisely while it lasts."],
  ["Standstill", "Pǐ", "Stagnation, when the same forces that created Peace have drifted apart and stopped communicating. Progress stalls until the underlying disconnect is addressed.", "Heaven and earth do not unite: the image of a standstill, where what is above and what is below have lost touch with each other.", "This isn't the moment to force forward motion. Withdraw a little, conserve your resources, and focus on realigning what has drifted apart — the standstill will pass."],
  ["Fellowship with Others", "Tóng Rén", "Genuine community formed around shared purpose, open to all who sincerely belong — not a closed clique. Fellowship built on real principle endures; fellowship built on convenience does not.", "Heaven together with fire: the image of people uniting under an open sky, visible to all.", "Look for allies who share your actual purpose, not just your convenience. Keep the association open and honest, and the fellowship will prove far more resilient."],
  ["Possession in Great Measure", "Dà Yǒu", "Abundance held with humility. Great resources or influence, but the hexagram's favor depends on using that abundance generously rather than hoarding or flaunting it.", "Fire high in heaven: the image of the sun illuminating everything below it equally.", "Whatever you've gained, let it serve more than yourself. Generosity and modesty are what keep abundance from turning into isolation or resentment."],
  ["Modesty", "Qiān", "The rare hexagram with no unfavorable lines at all — genuine humility, especially from someone who has real ability, is one of the safest and most respected positions to hold.", "Within the earth, a mountain: the image of greatness that keeps itself low.", "Whatever strength or success you're carrying, wear it lightly. Modesty here isn't self-erasure — it's quiet confidence that doesn't need to announce itself."],
  ["Enthusiasm", "Yù", "Inspired, harmonious momentum — the kind of energy that moves groups and organizes effort willingly, without coercion, when it comes from a sincere source.", "Thunder comes resounding out of the earth: the image of enthusiasm that stirs everything around it into motion.", "If your intentions are sincere, don't be afraid to let your enthusiasm show — it's genuinely persuasive right now. Just stay grounded so it doesn't tip into carelessness."],
  ["Following", "Suí", "Willingly adapting to what the moment calls for, rather than insisting on your own fixed course. Real strength here is knowing when to yield direction to someone or something else.", "Thunder within the lake: the image of movement that adapts and settles, following the shape of what surrounds it.", "Flexibility serves you better than stubbornness right now. Follow the guidance, person, or circumstance that has earned your trust, and stay willing to adjust course."],
  ["Work on What Has Been Spoiled", "Gǔ", "Decay that has set in through neglect, now requiring real, deliberate repair. Not a punishment — an invitation to finally address what's been left to drift.", "Wind at the foot of the mountain: the image of stagnant air gathering until it must be cleared.", "Something has been neglected and needs honest attention now, whether that's a relationship, a habit, or a plan. Address the root cause directly rather than patching the surface."],
  ["Approach", "Lín", "Growing, advancing influence — a favorable season arriving, though it calls for using new strength wisely rather than assuming it will last unchecked.", "The earth above the lake: the image of one thing drawing near to another, approaching with warmth.", "An opportunity or relationship is drawing closer and gaining strength. Meet it with sincerity rather than complacency, and remember that every season of growth eventually turns."],
  ["Contemplation", "Guān", "Stepping back to observe with clear, unhurried perspective — like standing at a height and surveying the whole landscape before acting.", "Wind moves over the earth: the image of something felt everywhere at once, the way careful observation quietly informs everyone around it.", "Resist the urge to act immediately. Take the wider view first — what you understand by observing carefully now will shape a far better decision than acting on impulse."],
  ["Biting Through", "Shì Kè", "Removing an obstacle that is actively blocking progress, decisively and through legitimate means — like biting through something stuck between the teeth.", "Thunder and lightning: the image of clear, decisive force used to resolve an obstruction.", "Something is standing in the way and needs to be dealt with directly, not avoided. Address it firmly and fairly, and the path forward will open."],
  ["Grace", "Bì", "Beauty and refinement in form — but the hexagram cautions that surface elegance must rest on real substance, or it becomes hollow decoration.", "Fire at the foot of the mountain: the image of light that illuminates a form without changing its essential nature.", "Presentation matters right now, but don't let it outrun the substance underneath. Refine how you communicate your intentions, while making sure the intentions themselves are sound."],
  ["Splitting Apart", "Bō", "Decline and erosion, when a structure has been weakened from within until collapse becomes hard to avoid. The wise response is retreat and patience, not resistance.", "The mountain rests on the earth, worn away: the image of a structure being slowly eroded from its base.", "This is not the moment to push against a decline that is already underway. Preserve what you can, step back from the crumbling structure, and wait for the moment to rebuild."],
  ["Return", "Fù", "The turning point — after a period of decline, a single new, positive impulse re-emerges at the very bottom, marking the start of renewal.", "Thunder within the earth: the image of the winter solstice, the moment new light begins to return.", "A difficult cycle is beginning to turn. The change may be small at first, but it's real — nurture it gently rather than forcing a full recovery all at once."],
  ["Innocence", "Wú Wàng", "Acting from genuine, spontaneous integrity rather than calculation. Favorable when your motives are honest; unfavorable if you try to force outcomes that aren't naturally yours to control.", "Under heaven, thunder rolls: the image of an instinctive, natural movement, free of scheming.", "Trust your honest instincts here rather than overthinking or manipulating the outcome. What comes from genuine motive will find its own right result."],
  ["The Taming Power of the Great", "Dà Chù", "Great strength held in check by equally great discipline. Restraint isn't weakness here — it's what allows real power to be stored up and used well when the time comes.", "Heaven within the mountain: the image of immense strength contained and accumulated.", "You have real capability building up — the discipline is in not releasing it too soon. Study, prepare, and hold steady; the accumulated strength will serve you fully when it's time."],
  ["Nourishment", "Yí", "What and how you feed yourself and others — physically, intellectually, and in character. The hexagram asks you to examine the source and quality of what you're taking in.", "Thunder at the foot of the mountain: the image of the mouth, and of the careful attention nourishment deserves.", "Pay attention to what you're feeding your mind, body, and relationships right now. Provide for others generously, but also be honest about what you truly need to sustain yourself."],
  ["Preponderance of the Great", "Dà Guò", "A structure under exceptional strain — the middle carries too much weight for the ends to support. A critical, unusual situation calling for decisive, careful action.", "The lake rises above the trees: the image of pressure beyond the ordinary measure.", "You're carrying more than the usual load right now. Act decisively where you must, but be honest about which supports are genuinely strong enough to bear the weight."],
  ["The Abysmal", "Kǎn", "Danger repeated, like water flowing through a deep gorge — but water also always finds its way through. The hexagram teaches how to move safely through genuine risk.", "Water flows on uninterrupted: the image of danger met with steady, unwavering sincerity.", "You're moving through a genuinely difficult passage. Stay honest and consistent rather than looking for shortcuts — like water, steady persistence is what carries you through danger."],
  ["The Clinging", "Lí", "Radiant clarity that, like fire, needs something to attach to in order to burn. Brightness and dependence are linked here — clarity of purpose comes through what you devote yourself to.", "Fire following fire: the image of brightness sustained by continual attachment to what feeds it.", "Clarify what you're truly devoted to right now, because that devotion is what will carry your light. Illuminate the situation honestly, and let your commitment give it lasting warmth."],
  ["Influence", "Xián", "Mutual attraction and responsiveness, the way a young man and woman are drawn to each other — spontaneous, sincere connection rather than one side pursuing the other.", "A mountain with a lake above it: the image of open receptivity, drawing others near.", "If you want genuine connection, be sincerely open rather than pursuing it forcefully. Real influence works both ways — it invites a response rather than demanding one."],
  ["Duration", "Héng", "Endurance built on consistency of character, not rigidity. What lasts does so because its underlying principle stays constant even as its outward expression adapts.", "Thunder and wind together: the image of steady, mutually reinforcing movement that renews itself.", "Whatever you're building now, focus on making its foundation consistent rather than perfect. Durability comes from steady character over time, not from a single dramatic effort."],
  ["Retreat", "Dùn", "A strategic, timely withdrawal — not defeat, but the wisdom to disengage from a losing position while you can still do so with dignity and strength intact.", "Mountain beneath heaven: the image of something small withdrawing gracefully before something greater.", "If a situation is turning against you, this is the moment to withdraw deliberately rather than dig in. A graceful retreat now preserves your strength for a better opportunity later."],
  ["The Power of the Great", "Dà Zhuàng", "Great strength on the rise — genuinely powerful, but the hexagram warns against using that power carelessly or aggressively. True strength stays within what is right.", "Thunder above heaven: the image of great power in motion, needing to be guided by principle.", "You have real momentum and strength available right now. Use it deliberately and fairly rather than forcefully — power used well earns lasting respect; power misused invites resistance."],
  ["Progress", "Jìn", "Steady, visible advancement, like the sun rising over the earth — recognition and forward motion come naturally when your conduct stays clear and correct.", "The sun rises over the earth: the image of brightness advancing and becoming ever more visible.", "This is a favorable season to move forward openly. Keep your conduct clear and your motives visible, and the progress you're making will be recognized rather than doubted."],
  ["Darkening of the Light", "Míng Yí", "A time when clarity or integrity must be deliberately concealed to survive a difficult environment — like a light hidden within, protected until it's safe to shine again.", "The light has sunk into the earth: the image of brightness that must be guarded rather than displayed.", "This isn't the moment to broadcast your true position or intentions. Protect your integrity quietly from within, and wait for a safer time before you let it show outwardly again."],
  ["The Family", "Jiā Rén", "Order and warmth within a household or close community, where each member fulfills their role with sincerity. Strong families and teams are built on this kind of mutual responsibility.", "Wind comes from fire: the image of influence that spreads outward from a well-ordered center.", "Strengthen the close relationships you rely on by being reliable within them yourself. A stable center, built on mutual respect and clear roles, supports everything that extends from it."],
  ["Opposition", "Kuí", "Estrangement and misunderstanding between people who nonetheless share common ground, if they can find it. Progress comes through small, careful reconciliations, not grand gestures.", "Fire above, the lake below: the image of two things moving in different directions, that still might meet.", "Don't try to force full agreement where there's real friction. Look instead for small, honest points of common ground — reconciliation here happens gradually, not all at once."],
  ["Obstruction", "Jiǎn", "A genuine external difficulty — like a mountain in your path — that cannot be pushed through directly. The wise response is to pause, reassess, and seek wise counsel.", "Water on top of the mountain: the image of a difficult, halting path forward.", "Don't force your way through this obstacle directly. Pause, seek honest advice from someone wiser, and look for the safer path around the difficulty rather than through it."],
  ["Deliverance", "Xiè", "Release from tension after a period of difficulty — like a storm finally breaking. The moment calls for prompt, decisive action to resolve what remains before it settles again.", "Thunder and rain set in: the image of built-up tension finally releasing.", "The pressure is starting to lift. Use this window to resolve what remains decisively and to forgive what's passed — don't let old tension linger once the storm has actually broken."],
  ["Decrease", "Sǔn", "Deliberately giving something up now — resources, comfort, ego — in order to strengthen what matters more. Sincere, well-placed sacrifice is not loss; it's investment.", "The mountain above the lake: the image of what is below being drawn upon to enrich what is above.", "Consider what you might sincerely let go of right now to strengthen something more important. Handled with the right intention, this kind of sacrifice returns more than it costs."],
  ["Increase", "Yì", "A favorable season of genuine growth, often when those above give generously to those below. Momentum is real, so act while conditions actively support you.", "Wind and thunder together: the image of forces reinforcing each other, amplifying growth.", "Conditions are genuinely in your favor for growth right now — use the momentum. If you're in a position to give generously to others, that generosity will come back amplified."],
  ["Breakthrough", "Guài", "A decisive, resolute stand against a last remaining difficulty. The situation strongly favors you, but the hexagram warns against arrogance in victory.", "The lake rises to heaven: the image of an overwhelming, decisive force about to break through.", "You have the advantage now, and it's time to act on it decisively. Just resolve the situation firmly and fairly — don't let confidence tip into carelessness at the final moment."],
  ["Coming to Meet", "Gòu", "An unplanned, potentially destabilizing encounter or influence entering the picture. Not automatically bad, but it needs to be recognized and handled with awareness, not naivety.", "Wind under heaven: the image of an influence moving quietly through everything it touches.", "Something unexpected has entered the picture, and it deserves clear-eyed attention. Don't dismiss it, but don't let it take hold unchecked either — meet it consciously."],
  ["Gathering Together", "Cuì", "People or resources drawing together around a shared, worthy center. Favorable for cooperation and collective effort, provided the gathering has genuine, sincere leadership.", "The lake rises above the earth: the image of things naturally collecting where the ground is lowest.", "This is a good time to bring people together around a shared purpose. Lead the gathering with sincerity, and prepare properly — real strength comes from unity, not just numbers."],
  ["Pushing Upward", "Shēng", "Gradual, steady ascent, like a plant growing upward through the earth — not sudden, but genuine and cumulative. Effort applied consistently now yields real advancement.", "Wood grows within the earth: the image of gradual, steady upward growth.", "Growth here is gradual, not explosive, and that's fine. Keep applying steady, honest effort, and don't get discouraged by how slow the visible progress feels."],
  ["Oppression", "Kùn", "Exhaustion and constraint, when your resources or options are genuinely limited. The hexagram's counsel is inner steadiness — keep your integrity even when your circumstances are compressed.", "The lake is empty of water: the image of exhaustion, and of the need to draw on inner reserves.", "Circumstances are genuinely constrained right now, and pushing harder against them may not help. Preserve your inner composure and integrity — that's what will see you through to easier ground."],
  ["The Well", "Jǐng", "A steady, communal source of nourishment, drawn upon by everyone, that doesn't diminish with use — but only if it's kept clear and properly maintained.", "Water above wood: the image of a well drawing water up to nourish everyone who comes to it.", "Take care of the resource, skill, or relationship that consistently nourishes you and others. Keep it well-maintained, because its value depends on being kept clear and accessible."],
  ["Revolution", "Gé", "Fundamental, necessary change — like the changing of the seasons. When an old arrangement has genuinely stopped working, decisive transformation is called for, at the right moment.", "Fire within the lake: the image of two elements in genuine tension, driving real transformation.", "If something in your life has fundamentally stopped working, this favors real change rather than a patch. Choose your timing and reasons carefully, then commit to the transformation fully."],
  ["The Cauldron", "Dǐng", "Transformation through refinement — like raw ingredients turned into nourishment by fire. Represents culture, structure, and the steady work of turning potential into something of real value.", "Fire above wood: the image of a vessel that transforms raw material into nourishment.", "This favors steady, deliberate refinement of what you already have, turning raw effort into something genuinely valuable. Build stable structure around your goals rather than rushing the process."],
  ["The Arousing", "Zhèn", "Sudden shock or upheaval, like thunder — startling at first, but ultimately clarifying. The right response is composed alertness rather than panic.", "Thunder repeated: the image of shock that, once past, leaves clarity behind it.", "Something sudden may unsettle you right now, but don't mistake the shock for lasting danger. Stay composed through it, and you'll find real clarity once the initial disruption passes."],
  ["Keeping Still", "Gèn", "Deliberate stillness — knowing when not to act, and being fully present where you are rather than reaching toward what's ahead or behind. Stillness as strength, not passivity.", "Mountains standing together: the image of stillness that holds its position without straining.", "This is a moment to be still rather than to push forward. Stay genuinely present with where things are right now, without straining toward what's next — clarity comes from the pause."],
  ["Development", "Jiàn", "Gradual, correct progress, like a tree growing steadily or a courtship unfolding at its proper pace. Rushing this process undermines it; patience secures it.", "A tree on the mountain grows slowly: the image of gradual development that reaches its proper height in its own time.", "Let this situation develop at its natural pace rather than forcing it faster. Gradual, correctly ordered progress will hold; anything rushed here is more likely to come apart."],
  ["The Marrying Maiden", "Guī Mèi", "A situation entered into with an unclear or subordinate position — proceed with extra awareness and care, since the usual footing isn't fully secure.", "Thunder above the lake: the image of movement that stirs what lies beneath it.", "Be honest with yourself about where you actually stand in this situation before committing further. Proceeding with clear eyes and genuine care matters more than moving quickly."],
  ["Abundance", "Fēng", "A peak season of fullness and clarity — but the hexagram reminds that all abundance is a phase in a cycle, like the sun at noon, already beginning its next movement.", "Thunder and lightning together: the image of a moment of great, illuminating fullness.", "Enjoy and make full use of this abundant season, but stay clear-eyed that it is a season, not a permanent state. Use the fullness now to build something that will outlast it."],
  ["The Wanderer", "Lǚ", "A traveler without a settled home base, needing to rely on adaptability, modesty, and careful conduct rather than established standing.", "Fire on the mountain: the image of a flame that moves on rather than settling into one place.", "In unfamiliar territory, adaptability and quiet good conduct will serve you better than asserting authority you haven't yet earned there. Travel light, and treat the situation with respect."],
  ["The Gentle", "Xùn", "Influence exercised gradually and penetratingly, like wind — subtle rather than forceful, but capable of reaching everywhere given enough persistence.", "Winds follow one another: the image of gentle, repeated influence that eventually reaches everything.", "Persuasion and steady, gentle persistence will serve you better right now than force or ultimatums. Keep applying quiet, consistent influence — it reaches further than a single strong push."],
  ["The Joyous", "Duì", "Genuine, open joy shared with others — but the hexagram cautions that joy must stay sincere and grounded, not indulgent or used to manipulate.", "Lakes resting together: the image of joy that reinforces itself when it's shared openly.", "Share what's genuinely bringing you joy right now with the people around you — sincerity is what makes it meaningful rather than shallow. Just keep it honest, not performative."],
  ["Dispersion", "Huàn", "Dissolving what has become rigid, scattered, or divided — bringing fragmented parts back into a coherent whole through sincere, unifying effort.", "Wind moves over water: the image of something scattered being gently gathered back together.", "If something has become fragmented — a team, a plan, a relationship — this favors patient, sincere effort to bring the pieces back together, rather than forcing a rigid structure onto it."],
  ["Limitation", "Jié", "Necessary boundaries and restraint, like the fixed banks that give a river its direction and power. Limits used wisely create structure; used excessively, they become confinement.", "Water above the lake: the image of a boundary that gives shape and containment to what it holds.", "Setting clear, reasonable limits right now — on your time, resources, or commitments — will serve you better than trying to do everything. Just avoid limits so strict they become their own burden."],
  ["Inner Truth", "Zhōng Fú", "Sincerity so genuine it reaches and moves even those who are naturally distant or skeptical — like trust that a wild bird can somehow sense.", "Wind over the lake: the image of an influence felt inwardly before it's ever seen outwardly.", "Lead with real sincerity in this situation rather than strategy or persuasion technique. Genuine inner truth communicates itself, often more effectively than any argument could."],
  ["Preponderance of the Small", "Xiǎo Guò", "Attention to small, careful details rather than grand gestures — like a bird flying low rather than attempting heights it isn't ready for yet.", "Thunder on the mountain: the image of a sound that carries further by staying close to the ground.", "This favors modest, careful attention to detail over bold, sweeping action. Handle the small things conscientiously right now — reaching for something grander would overextend you."],
  ["After Completion", "Jì Jì", "A goal successfully achieved and everything in its proper order — but the hexagram's real warning is that order, once achieved, tends to quietly start unraveling if left unattended.", "Water above fire: the image of a completed, balanced order that still requires ongoing care.", "Having reached this point of success or order, don't assume it will simply maintain itself. Stay attentive to the details even now — that ongoing care is what keeps completion from quietly slipping."],
  ["Before Completion", "Wèi Jì", "The final hexagram: things are almost, but not quite, in order — real progress made, with the crucial last steps still requiring care and patience before completion is secure.", "Fire above water: the image of forces not yet in their proper place, still finding their right order.", "You're genuinely close, but this isn't the moment to relax the final effort. Take the last steps carefully and in the right order, and the completion you're working toward will hold."],
];

export const HEXAGRAMS = RAW.map((entry, i) => {
  const number = i + 1;
  const [name, pinyin, judgment, image, guidance] = entry;
  const slug = `${number}-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}`;
  return { number, name, pinyin, symbol: symbol(number), slug, judgment, image, guidance };
});
